Name:           perl-PurpleWiki
Version:        0.94
Release:        1%{?dist}
Summary:        PurpleWiki Perl module
License:        GPLv2+

Group:          Development/Libraries
URL:            http://search.cpan.org/dist/PurpleWiki/
Source0:        http://www.cpan.org/authors/id/C/CD/CDENT/PurpleWiki/PurpleWiki-%{version}.tar.gz
Patch0:         PurpleWiki-0.94-nocgi.patch
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))


%description
PurpleWiki is a WikiWikiWeb that adds purple numbers to paragraphs,
headers, lists, and other fine-grained elements on a Wiki page.  These
numbers can be used to create links to these specific elements.


%package Parser
Summary:        PurpleWiki Parsers
Group:          Development/Libraries

%description Parser
PurpleWiki Parsers.


%package View
Summary:        PurpleWiki Views
Group:          Development/Libraries

%description View
PurpleWiki Views.


%package core
Summary:        PurpleWiki Core
Group:          Development/Libraries

%description core
PurpleWiki Core.


%prep
%setup -q -n PurpleWiki-%{version}
%patch0 -p1 -b .nocgi


%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}


%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*


%check
#make test


%clean
rm -rf $RPM_BUILD_ROOT


%files
%defattr(-,root,root,-)
%{perl_vendorlib}/PurpleWiki/Search
%{perl_vendorlib}/PurpleWiki/Template
%{perl_vendorlib}/PurpleWiki/ACL.pm
%{perl_vendorlib}/PurpleWiki/Apache1Handler.pm
%{perl_vendorlib}/PurpleWiki/Apache2Handler.pm
%{perl_vendorlib}/PurpleWiki/NidHandler.pm
%{perl_vendorlib}/PurpleWiki/Syndication/Rss.pm
%{perl_vendorlib}/wiki.pl
%{_mandir}/man3/PurpleWiki::Search::*.3pm*
%{_mandir}/man3/PurpleWiki::Template::*.3pm*
%{_mandir}/man3/PurpleWiki::ACL.3pm*
%{_mandir}/man3/PurpleWiki::Apache1Handler.3pm*
%{_mandir}/man3/PurpleWiki::Apache2Handler.3pm*
%{_mandir}/man3/PurpleWiki::NidHandler.3pm*
%{_mandir}/man3/PurpleWiki::Syndication::Rss.3pm*


%files Parser
%{perl_vendorlib}/PurpleWiki/Parser
%{_mandir}/man3/PurpleWiki::Parser::*.3pm*


%files View
%{perl_vendorlib}/PurpleWiki/View
%{_mandir}/man3/PurpleWiki::View::*.3pm*


%files core
%{perl_vendorlib}/PurpleWiki/Config.pm
%{perl_vendorlib}/PurpleWiki/Singleton.pm
%{perl_vendorlib}/PurpleWiki/Transclusion.pm
%{perl_vendorlib}/PurpleWiki/Tree.pm
%{perl_vendorlib}/PurpleWiki/Sequence.pm
%{perl_vendorlib}/PurpleWiki/StructuralNode.pm
%{perl_vendorlib}/PurpleWiki/InlineNode.pm
%{perl_vendorlib}/PurpleWiki/Page.pm
%{perl_vendorlib}/PurpleWiki/Database
%{perl_vendorlib}/PurpleWiki/Database.pm
%{perl_vendorlib}/PurpleWiki/User.pm
%{_mandir}/man3/PurpleWiki::Config.3pm*
%{_mandir}/man3/PurpleWiki::Singleton.3pm*
%{_mandir}/man3/PurpleWiki::Transclusion.3pm*
%{_mandir}/man3/PurpleWiki::Tree.3pm*
%{_mandir}/man3/PurpleWiki::Sequence.3pm*
%{_mandir}/man3/PurpleWiki::StructuralNode.3pm*
%{_mandir}/man3/PurpleWiki::InlineNode.3pm*
%{_mandir}/man3/PurpleWiki::Database*.3pm*
%{_mandir}/man3/PurpleWiki::User.3pm*
%%doc ChangeLog Contributors LICENSE README UPGRADE

%changelog
* Wed Mar 11 2009 Lubomir Rintel <lkundrak@v3.sk> 0.94-1
- Specfile autogenerated by cpanspec 1.77.
- Disable installation of the CGI
